### ISSUE TITLE
Version conflict running honeycomb's opentelemetry-instrument

### ISSUE THREAD

**Issue by guillemtrebol** [honeycombio/honeycomb-opentelemetry-python#123]
**Versions**
[v0.1.2b0](https://github.com/honeycombio/honeycomb-opentelemetry-python/releases/tag/v0.1.2b0)

**Steps to reproduce**

I am trying to run a Honeycomb + OpenTelemetry instrumented Flask app following the documentation on the docs here, as of April 4th 2023.
https://docs.honeycomb.io/getting-data-in/opentelemetry/python-distro/#automatic-instrumentation

I have built a Docker image as described here:

Dockerfile:
```
FROM python:3.9

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install honeycomb-opentelemetry --pre
RUN opentelemetry-bootstrap --action=install

COPY . /app

ENTRYPOINT ["opentelemetry-instrument", "python","/app/app.py"]
EXPOSE 5000
```

requirements.txt:
```
Flask==2.0.2
```

app.py:
```
from flask import Flask, jsonify, request
from opentelemetry import trace
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider

# Set up tracer
resource = Resource.create({"service.name": "my-service"})
trace.set_tracer_provider(TracerProvider(resource=resource))

# Define routes for the Flask app
app = Flask(__name__)


@app.route("/")
def index():
    return "Welcome to my Flask app!"


@app.route("/hello")
def hello():
    return jsonify({"message": "Hello, world!"})


@app.route("/user/<username>")
def user_profile(username):
    user_agent = request.headers.get("User-Agent")
    with trace.get_tracer(__name__).start_as_current_span("user_profile"):
        # Do some work here...
        return jsonify({"username": username, "user_agent": user_agent})


if __name__ == "__main__":
    app.run(host='0.0.0.0')
```

When running the application with this command, with Honeycomb debugging active:
`docker container run -p 5000:5000 -e DEBUG=true flask_test`

the following inconsistency with versions appears even before Flask starts:

```
Distribution distro configuration failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 37, in _load_distros
    distro = entry_point.load()()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (opentelemetry-sdk 1.16.0 (/usr/local/lib/python3.9/site-packages), Requirement.parse('opentelemetry-sdk~=1.17.0'), {'opentelemetry-exporter-otlp-proto-grpc', 'opentelemetry-exporter-otlp-proto-
http'})
Failed to auto initialize opentelemetry
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 119, in initialize
    distro = _load_distros()
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 52, in _load_distros
    raise exc
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 37, in _load_distros
    distro = entry_point.load()()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (opentelemetry-sdk 1.16.0 (/usr/local/lib/python3.9/site-packages), Requirement.parse('opentelemetry-sdk~=1.17.0'), {'opentelemetry-exporter-otlp-proto-grpc', 'opentelemetry-exporter-otlp-proto-
http'})
```

**Comment by guillemtrebol** [comment]
I have just tried to follow the configuration stated on issue #109, and the dependency problem seems to be solved.

My concern here is: will Alpha `honeycomb-opentelemetry==0.1.1a3` continue to be available in the future? is it better to use another method to instrument my app while `honeycomb-opentelemetry` is in beta mode?

**Comment by robbkidd** [comment]
Hi @guillemtrebol!

We won't be yanking v0.1.1a3. We did yank some of the very early alpha versions mostly because they didn't do anything, we were just exercising a new publishing pipeline. v0.1.1a3 was the release candidate for v0.1.2b0 and is functionally equivalent. If you've got an arrangement of versions that are working for you at the moment, that is a package that will be available for the foreseeable future.

I've been thinking that `requirements.txt` ought to track an application's dependency on the `honeycomb-opentelemetry` package, the `opentelemetry-api` package (if adding custom instrumentation to your app), and the instrumentation packages that are detected and installed by `opentelemetry-bootstrap --action=install`. We've done [the equivalent declaration with poetry in the example flask app](https://github.com/honeycombio/honeycomb-opentelemetry-python/blob/v0.1.2b0/examples/hello-world-flask/pyproject.toml#L11-L13). These version conflicts could then be discovered in the development environment as opposed to during image build and run. `opentelemetry-bootstrap`'s default action is to print what instrumentations would be useful for an app to the console in a format that can be added to `requirements.txt`.

We're discussing updating the documentation to reflect this approach of treating the SDK and instrumentation packages as app dependencies instead of runtime add-ons. What do you think about that approach?

**Comment by guillemtrebol** [comment]
Hi @robbkidd,

Thanks a lot for your comments! I've been working more on this problem, and I may have found the root of the problem here. 

As you state on [pypy.org's honeycomb-opentelemetry 0.1.2b0](https://pypi.org/project/honeycomb-opentelemetry/), this version is built with [OpenTelemetry 1.16.0/0.37b0](https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.16.0). Since OpenTelemetry recently released version `1.17.0/0.38b0`, I think that the installation process of `honeycomb-opentelemetry` accidentally installs some modules of the OpenTelemetry's newer version, which ends up causing the conflict version at runtime between `1.17.0` and `1.16.0` that I explained before.

To solve this problem, I manually forced the previous installation of OpenTelemetry `1.16.0` adding package `opentelemetry-sdk` on `requirements.txt`, leaving it like this:
```
Flask==2.0.2
opentelemetry-sdk==1.16.0
honeycomb-opentelemetry==0.1.2b0
```
This is how the `Dockerfile` ends up:
```
FROM python:3.9

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
RUN opentelemetry-bootstrap --action=install

COPY . /app
ENTRYPOINT ["opentelemetry-instrument", "python", "/app/flask_test.py"]
EXPOSE 5000
```

Unless having understood something wrong, I think that maybe you could build the next version of `honeycomb-opentelemetry` with OpenTelemetry `1.17.0`, but most importantly force the requirements to have the compatible versions of OpenTelemetry only.
I have created PR #125 if you would like to apply those changes.

To answer your question about the documentation: yes, I think it would be a lot clearer to the user to treat those packages as dependencies.
